name: Pull Request Validation

concurrency:
  group: pull_request_${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v7

      - name: Setup Danger Files
        run: |
          echo "Setting up Danger files..."
          rm -f ./dangerfile.ts
          cp tools/danger/dangerfile.js ./dangerfile.js
          cp tools/danger/package.json ./danger-package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Danger JS Action
        run: npx danger ci --dangerfile dangerfile.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
