name: Todo Checker

on:
  # Run this workflow on push to main
  push:
    branches:
      - main

# Restrict default permissions for all jobs (CKV2_GHA_1)
permissions: {}

jobs:
  todo:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Begin CI...
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@37bb7b56e58569ef273b60678048030a7f0c261a # v5.1.15
        id: todo
        with:
          INSERT_ISSUE_URLS: 'false'
          CLOSE_ISSUES: 'true'
